### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by josenimo** [SchapiroLabor/multiplex_macsima#1]
Dear @VictorDidier,

Thank you for developing this nice package. I am currently testing the docker container implementation and I am running into an isssue. I am using a small sample data set, which has 000 -> 003 cycles.  Thank you for your help and let me know what other information I can provide. 

Output before crashing (for every exposure level):
![image](https://github.com/SchapiroLabor/multiplex_macsima/assets/30318135/b80e0bb6-cae1-45f3-a199-9663b620d146)

```
(base) mambauser@b2a9af1b8e0f:/stack_macsima$ python macsima2mc.py -i /data -o /data/output -c 1 3
extracting antigen cycle: 1
extracting bleaching cycle: 0
extracting bleaching cycle: 0
extracting bleaching cycle: 0
extracting antigen cycle: 2
extracting bleaching cycle: 1
extracting bleaching cycle: 1
extracting bleaching cycle: 1
extracting antigen cycle: 3
Traceback (most recent call last):
  File "/stack_macsima/macsima2mc.py", line 611, in <module>
    main()
  File "/stack_macsima/macsima2mc.py", line 568, in main
    antigen_stack_info=create_stack(antigen_info,antigen_cycle_no=i,exp_level=e)
  File "/stack_macsima/macsima2mc.py", line 473, in create_stack
    exp=groupB.loc[(groupB['marker']==s) & (groupB['fov']==1) & (groupB['exposure_level']==exp_level),'exposure'].tolist()[0]
IndexError: list index out of range
```
Link to sample dataset:
https://filetransfer.mdc-berlin.de/?u=dTzagkaQ&p=C6fa7U32

Best,
Jose

**Comment by migueLib** [comment]
@josenimo We recently created a pip version to install macsima2mc could you perhaps try it (if you have time) and let us know if this fixed the issue?

**Comment by josenimo** [comment]
installation worked, will get my hands on some macsima data and let you know

**Comment by migueLib** [comment]
@VictorDidier and @josenimo 
Where are we standing here? Is this still an issue? Or can I close this issue?

**Comment by josenimo** [comment]
idk haha, can check again later today :)

**Comment by VictorDidier** [comment]
@migueLib and @josenimo the latest macsima2mc release uses the latest  BASICPY version, which doesn't use Jax anymore, it uses torch instead so this should not be a problem.  Or at least you should get a different error ,😅 .

**Comment by migueLib** [comment]
Then I'm closing this
